- name: Pull repo and recreate docker container
  hosts: all
  tasks:
    - name: Pull changes from git repository
      git:
        repo: https://github.com/School-58-IT-gen-2/quest_hub_telegram_app.git
        dest: /projects/dnd/quest_hub_telegram_app
        version: main

    - name: Build Docker image
      command: docker build -t quest_hub_telegram_app:main /projects/dnd/quest_hub_telegram_app

    - name: Stop old container
      command: docker compose -f /projects/dnd/quest_hub_telegram_app/docker-compose.yml down --remove-orphans

    - name: Run docker-compose up
      command: docker compose -f /projects/dnd/quest_hub_telegram_app/docker-compose.yml up -d --force-recreate

